### ISSUE TITLE
Hashrate is incorrect.

### ISSUE THREAD

**Issue by tuananh19961** [MarcoCiaramella/minotaurx-web#1]
```
const hashrate = `${e.data.data * NUM_WORKERS} Kh/s`;
print("hashrate:", hashrate);
socket.emit('hashrate', { hashrate: hashrate });
```

Hi @MarcoCiaramella . I'm trying increase "NUM_WORKERS" but hashrate is not shown correct on pool and it also doesn't help submit work faster. 

<img width="219" alt="Screen Shot 2024-03-05 at 16 08 32" src="https://github.com/MarcoCiaramella/minotaurx-web/assets/40750548/30aa39ac-994f-4da3-a2e8-25f1d32155ee">
<img width="846" alt="Screen Shot 2024-03-05 at 16 09 37" src="https://github.com/MarcoCiaramella/minotaurx-web/assets/40750548/b902bf46-d6de-4f6a-9933-7fa06cc3e369">

**Comment by tuananh19961** [comment]
Hi, @MarcoCiaramella 
I think both of them.
I'm trying increase NUM_WORKERS = 4 but it not sự khác biệt with NUM_WORKERS = 1 in resolve work from pool.

**Comment by tuananh19961** [comment]
Hi, @MarcoCiaramella 
I think both of them.
I'm trying increase NUM_WORKERS = 4 but it it not difference with NUM_WORKERS = 1 in resolve work from pool.

**Comment by MarcoCiaramella** [comment]
this is not an issue. The hashrate logged out is from one worker not the total. I see it is a little bit confusing so I'm going to release a new version where hashrate is more clear

**Comment by tuananh19961** [comment]
Hi @MarcoCiaramella . Can we implement run mining on multi threads on this? Use multiple workers in parallel? I think it can be improve hashrate.

**Comment by MarcoCiaramella** [comment]
Hello @tuananh19961  it's already multi threding. In my test I see an higher hashrate on pool stats when run 4 web workers than 1.  On which pool you are testing? Can you provide me hashrate from pool with 1 and 4 web workers? Thanks!

**Comment by tuananh19961** [comment]
@MarcoCiaramella . As you see, I'm using 1 connection with 4 workers.

it mean when receive a job from pool, each worker will resolve the job independently and when one worker finishes resolving, the remaining workers will be interrupted and submit shared.

This is what I thought when studying the code here. If there is anything wrong, please forgive me.

<img width="1068" alt="Screen Shot 2024-03-06 at 14 50 10" src="https://github.com/MarcoCiaramella/minotaurx-web/assets/40750548/105f2e0a-78d2-4dd9-9ab6-3e495ecd7b93">
<img width="468" alt="Screen Shot 2024-03-06 at 14 49 45" src="https://github.com/MarcoCiaramella/minotaurx-web/assets/40750548/15709e4a-ca5c-44b8-b243-dc1a623ad2fe">

**Comment by MarcoCiaramella** [comment]
yes it is right. Each worker resolves the job independently and when one of them founds the share the main thread close the web workers running and submit the solution. This is the multi-threading mining implemented with web worker. More threads are running more solution you test and this translate to a higher hashrate. It is the standard multi-threading mining.
If you have 4 web workers you will see on log 4 times the hashrate X Kh/s and on pool stats you will see about 4 * X Kh/s.

Also note that hashrate is upper-bounded by the number of cores. If you have a CPU with 4 cores running 4 or more web workers results in the same hashrate.

**Comment by tuananh19961** [comment]
Thank @MarcoCiaramella . Cleared. Thank you so much.
